f = str(input('Digite uma frase: ')).strip()
f1 = f.lower()
print('A palavra aparece {} vezes na frase.'.format(f1.count('a')))
print('A primeira letra A apareceu na posiçao {} '.format(f1.find('a')+1))
print('A última letra A aparece na posição {}'.format(f1.rfind('a')+1))